import paramiko  
c=paramiko.SSHClient()  
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())  
c.connect('91.98.230.33',1221,'spored3v','REDACTED_SET_GOONSGEAR_SSH_PASSWORD')  
s=c.open_sftp()  
s.put('resources/views/shop/show.blade.php','/home/macaw-goonsgear/htdocs/goonsgear.macaw.studio/resources/views/shop/show.blade.php')  
s.put('app/Console/Commands/AssignVariantTypes.php','/home/macaw-goonsgear/htdocs/goonsgear.macaw.studio/app/Console/Commands/AssignVariantTypes.php')  
s.close()  
print('Re-running variant type assignment...')  
i,o,e=c.exec_command('cd /home/macaw-goonsgear/htdocs/goonsgear.macaw.studio && php artisan variants:assign-types',timeout=120)  
result=o.read().decode()  
print(result)  
c.exec_command('rm -rf /home/macaw-goonsgear/htdocs/goonsgear.macaw.studio/storage/framework/views/*')  
i,o,e=c.exec_command('cd /home/macaw-goonsgear/htdocs/goonsgear.macaw.studio && php artisan optimize:clear')  
print('\\nAll caches cleared - site ready')  
c.close()  
