import paramiko  
c=paramiko.SSHClient()  
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())  
c.connect('91.98.230.33',1221,'spored3v','HNjp0cfsKOZ9PoJltRvU')  
s=c.open_sftp()  
s.put('app/Console/Commands/AssignVariantTypes.php','/home/macaw-goonsgear/htdocs/goonsgear.macaw.studio/app/Console/Commands/AssignVariantTypes.php')  
s.close()  
print('Running variant assignment...')  
i,o,e=c.exec_command('cd /home/macaw-goonsgear/htdocs/goonsgear.macaw.studio && php artisan variants:assign-types',timeout=120)  
print(o.read().decode())  
i,o,e=c.exec_command('cd /home/macaw-goonsgear/htdocs/goonsgear.macaw.studio && php artisan optimize:clear')  
print('Caches cleared')  
c.close()  
